name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.1

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run checks
      run: |
        python manage.py check
        python manage.py test